Test github cache for data

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,8 +10,6 @@ jobs:
     env:
       IRACING_EMAIL: ${{ secrets.IRACING_EMAIL }}
       IRACING_PASSWORD: ${{ secrets.IRACING_PASSWORD }}
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       BASE_URL: "https://yvon.github.io/iracing-data-api-client/"
 
     steps:
@@ -22,27 +20,24 @@ jobs:
         with:
           ruby-version: '3.2.2'
 
-      - name: Download previous data
-        uses: s3-actions/aws-cli@v1
+      - name: Configure cache
+        id: cache-data
+        uses: actions/cache@v3
         with:
-          aws-command: s3 cp s3://iracing-data/data.tgz data.tgz
-        continue-on-error: true
+          path: data.tgz
+          key: data-${{ github.run_id }}
+          restore-keys: |
+            data-
 
       - name: Extract data
         run: |
-          mkdir -p data
-          test -f data.tgz && tar -xzf data.tgz || echo "Missing artifact"
+          test -f data.tgz && tar -xzf data.tgz || echo "Missing data"
 
       - name: Build the site
         run: rake build
 
       - name: Compress data
         run: tar -czf data.tgz data
-
-      - name: Archive data
-        uses: s3-actions/aws-cli@v1
-        with:
-          aws-command: s3 cp data.tgz s3://iracing-data/data.tgz
 
       - name: Upload artifact
         # Automatically uploads an artifact from the './_site' directory by default
@@ -51,8 +46,8 @@ jobs:
   deploy:
     needs: build
     permissions:
-      pages: write      # to deploy to Pages
-      id-token: write   # to verify the deployment originates from an appropriate source
+      pages: write # to deploy to Pages
+      id-token: write # to verify the deployment originates from an appropriate source
     environment:
       name: github-pages
     runs-on: ubuntu-latest
